import { bootstrapApplication } from '@angular/platform-browser';
import { addIcons } from 'ionicons';
import {
	addCircleOutline,
	addOutline,
	alarmOutline,
	albumsOutline,
	alertCircleOutline,
	analyticsOutline,
	arrowBackOutline,
	arrowForward,
	arrowForwardOutline,
	arrowRedo,
	arrowUpOutline,
	bagHandleOutline,
	barChartOutline,
	briefcaseOutline,
	businessOutline,
	calendarNumberOutline,
	calendarOutline,
	callOutline,
	cameraOutline,
	chatbubble,
	chatbubbleEllipsesOutline,
	chatbubblesOutline,
	checkmarkCircle,
	checkmarkCircleOutline,
	checkmarkDoneOutline,
	checkmarkOutline,
	chevronDownOutline,
	chevronForwardOutline,
	chevronUpOutline,
	close,
	closeCircleOutline,
	closeOutline,
	cloudOfflineOutline,
	cloudUploadOutline,
	codeSlashOutline,
	colorPaletteOutline,
	createOutline,
	cubeOutline,
	diamondOutline,
	documentOutline,
	documentTextOutline,
	downloadOutline,
	ellipsisHorizontal,
	ellipsisHorizontalCircleOutline,
	eyeOutline,
	fileTrayOutline,
	filmOutline,
	flashOutline,
	gitNetworkOutline,
	globeOutline,
	gridOutline,
	headsetOutline,
	heart,
	imageOutline,
	imagesOutline,
	informationCircleOutline,
	layersOutline,
	linkOutline,
	listOutline,
	locateOutline,
	locationOutline,
	lockClosedOutline,
	logOutOutline,
	logoFacebook,
	logoGoogle,
	logoInstagram,
	logoLinkedin,
	logoYoutube,
	mailOutline,
	mapOutline,
	megaphoneOutline,
	moonOutline,
	paperPlaneOutline,
	peopleOutline,
	personAddOutline,
	personCircleOutline,
	personOutline,
	phonePortraitOutline,
	play,
	playCircleOutline,
	podiumOutline,
	powerOutline,
	pricetagOutline,
	pricetagsOutline,
	pulseOutline,
	radioOutline,
	refreshOutline,
	removeOutline,
	ribbonOutline,
	rocketOutline,
	schoolOutline,
	searchOutline,
	settingsOutline,
	shieldCheckmark,
	shieldCheckmarkOutline,
	sparklesOutline,
	star,
	statsChartOutline,
	storefrontOutline,
	sunnyOutline,
	ticketOutline,
	timeOutline,
	todayOutline,
	trashOutline,
	trendingUpOutline,
	trophyOutline,
	unlinkOutline,
	videocamOutline,
	walletOutline,
	warningOutline,
} from 'ionicons/icons';
import { appConfig } from './app/app.config';
import { AppComponent } from './app/app.component';

// Standalone Ionic only renders icons registered here. Every <ion-icon name>
// used in the app must be listed, or it shows up blank.
addIcons({
	'add-circle-outline': addCircleOutline,
	'add-outline': addOutline,
	'alarm-outline': alarmOutline,
	'albums-outline': albumsOutline,
	'alert-circle-outline': alertCircleOutline,
	'analytics-outline': analyticsOutline,
	'arrow-back-outline': arrowBackOutline,
	'arrow-forward': arrowForward,
	'arrow-forward-outline': arrowForwardOutline,
	'arrow-redo': arrowRedo,
	'arrow-up-outline': arrowUpOutline,
	'bag-handle-outline': bagHandleOutline,
	'bar-chart-outline': barChartOutline,
	'briefcase-outline': briefcaseOutline,
	'business-outline': businessOutline,
	'calendar-number-outline': calendarNumberOutline,
	'calendar-outline': calendarOutline,
	'call-outline': callOutline,
	'camera-outline': cameraOutline,
	'chatbubble': chatbubble,
	'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
	'chatbubbles-outline': chatbubblesOutline,
	'checkmark-circle': checkmarkCircle,
	'checkmark-circle-outline': checkmarkCircleOutline,
	'checkmark-done-outline': checkmarkDoneOutline,
	'checkmark-outline': checkmarkOutline,
	'chevron-down-outline': chevronDownOutline,
	'chevron-forward-outline': chevronForwardOutline,
	'chevron-up-outline': chevronUpOutline,
	'close': close,
	'close-circle-outline': closeCircleOutline,
	'close-outline': closeOutline,
	'cloud-offline-outline': cloudOfflineOutline,
	'cloud-upload-outline': cloudUploadOutline,
	'code-slash-outline': codeSlashOutline,
	'color-palette-outline': colorPaletteOutline,
	'create-outline': createOutline,
	'cube-outline': cubeOutline,
	'diamond-outline': diamondOutline,
	'document-outline': documentOutline,
	'document-text-outline': documentTextOutline,
	'download-outline': downloadOutline,
	'ellipsis-horizontal': ellipsisHorizontal,
	'ellipsis-horizontal-circle-outline': ellipsisHorizontalCircleOutline,
	'eye-outline': eyeOutline,
	'file-tray-outline': fileTrayOutline,
	'film-outline': filmOutline,
	'flash-outline': flashOutline,
	'git-network-outline': gitNetworkOutline,
	'globe-outline': globeOutline,
	'grid-outline': gridOutline,
	'headset-outline': headsetOutline,
	'heart': heart,
	'image-outline': imageOutline,
	'images-outline': imagesOutline,
	'information-circle-outline': informationCircleOutline,
	'layers-outline': layersOutline,
	'link-outline': linkOutline,
	'list-outline': listOutline,
	'locate-outline': locateOutline,
	'location-outline': locationOutline,
	'lock-closed-outline': lockClosedOutline,
	'log-out-outline': logOutOutline,
	'logo-facebook': logoFacebook,
	'logo-google': logoGoogle,
	'logo-instagram': logoInstagram,
	'logo-linkedin': logoLinkedin,
	'logo-youtube': logoYoutube,
	'mail-outline': mailOutline,
	'map-outline': mapOutline,
	'megaphone-outline': megaphoneOutline,
	'moon-outline': moonOutline,
	'paper-plane-outline': paperPlaneOutline,
	'people-outline': peopleOutline,
	'person-add-outline': personAddOutline,
	'person-circle-outline': personCircleOutline,
	'person-outline': personOutline,
	'phone-portrait-outline': phonePortraitOutline,
	'play': play,
	'play-circle-outline': playCircleOutline,
	'podium-outline': podiumOutline,
	'power-outline': powerOutline,
	'pricetag-outline': pricetagOutline,
	'pricetags-outline': pricetagsOutline,
	'pulse-outline': pulseOutline,
	'radio-outline': radioOutline,
	'refresh-outline': refreshOutline,
	'remove-outline': removeOutline,
	'ribbon-outline': ribbonOutline,
	'rocket-outline': rocketOutline,
	'school-outline': schoolOutline,
	'search-outline': searchOutline,
	'settings-outline': settingsOutline,
	'shield-checkmark': shieldCheckmark,
	'shield-checkmark-outline': shieldCheckmarkOutline,
	'sparkles-outline': sparklesOutline,
	'star': star,
	'stats-chart-outline': statsChartOutline,
	'storefront-outline': storefrontOutline,
	'sunny-outline': sunnyOutline,
	'ticket-outline': ticketOutline,
	'time-outline': timeOutline,
	'today-outline': todayOutline,
	'trash-outline': trashOutline,
	'trending-up-outline': trendingUpOutline,
	'trophy-outline': trophyOutline,
	'unlink-outline': unlinkOutline,
	'videocam-outline': videocamOutline,
	'wallet-outline': walletOutline,
	'warning-outline': warningOutline,
	// aliases used by the theme toggle
	moon: moonOutline,
	sunny: sunnyOutline,
});

bootstrapApplication(AppComponent, appConfig).catch((err) => console.error(err));
